[relaychain]
default_command = "/Users/lisheng/mygit/sub/polkadot-sdk/target/release/polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 1000

    [parachains.collator]
    name = "charlie"
    ws_port = 9988
    command = "/Users/lisheng/mygit/sub/polkadot-sdk-course-code/advance/lesson-5/target/release/parachain-template-node"

[[parachains]]
id = 1001

    [parachains.collator]
    name = "eve"
    ws_port = 9977
    command = "/Users/lisheng/mygit/sub/polkadot-sdk-course-code/advance/lesson-5/target/release/parachain-template-node"
